# Generated by Django 4.0.6 on 2022-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicevent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('REDACTION', 'Rédaction'), ('EN COURS DE SIGNATURE', 'En cours de signature'), ('SIGNE', 'Signé'), ('TERMINE', 'Terminé')], default=('REDACTION', 'Rédaction'), max_length=50),
        ),
        migrations.DeleteModel(
            name='ContractStatus',
        ),
    ]
