# Generated by Django 4.0.6 on 2022-08-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('1', 'Rédaction'), ('2', 'En cours de signature'), ('3', 'Signé'), ('4', 'Terminé')], default=('1', 'Rédaction'), max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_client', to='clients.client')),
            ],
        ),
    ]
