# Generated by Django 4.0.6 on 2022-08-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('1', 'Rédaction'), ('2', 'En cours de signature'), ('3', 'Signé'), ('4', 'Terminé')], default=('1', 'Rédaction'), max_length=50),
        ),
    ]
