# Generated by Django 4.0.6 on 2022-08-16 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('RED', 'Rédaction'), ('CS', 'En cours de signature'), ('S', 'Signé'), ('T', 'Terminé')], default=('RED', 'Rédaction'), max_length=50),
        ),
    ]
