# Generated by Django 4.0.6 on 2022-08-08 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('sales_contact', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
